# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-11 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobpost_app', '0005_industry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default='', max_length=20, null=True)),
                ('user_pass', models.CharField(default='', max_length=12, null=True)),
                ('company_name', models.CharField(default='', max_length=200, null=True)),
                ('contact_person', models.CharField(default='', max_length=200)),
                ('company_address', models.CharField(default='', max_length=300, null=True)),
                ('billing_address', models.CharField(default='', max_length=300, null=True)),
                ('contact_phone', models.CharField(default='', max_length=13, null=True)),
                ('contact_email', models.CharField(default='', max_length=100, null=True)),
                ('website', models.CharField(default='', max_length=200)),
                ('industry_type', models.ManyToManyField(null=True, to='jobpost_app.Industry')),
            ],
        ),
    ]
