# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-11 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='billing_address',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='employer',
            name='company_address',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='employer',
            name='company_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='employer',
            name='contact_email',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='employer',
            name='contact_person',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='employer',
            name='contact_phone',
            field=models.CharField(default='', max_length=13),
        ),
        migrations.AlterField(
            model_name='employer',
            name='user_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='employer',
            name='user_pass',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AlterField(
            model_name='employer',
            name='website',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
