# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-14 06:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer_app', '0002_auto_20170911_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='industry_type',
            field=models.ManyToManyField(to='jobpost_app.Industry'),
        ),
    ]
