# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-19 05:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobpost_app', '0007_category'),
        ('employer_app', '0003_auto_20170914_1234'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(default='', max_length=200)),
                ('vacancies', models.IntegerField(default=1)),
                ('with_photo', models.BooleanField(default=True)),
                ('apply_ins', models.CharField(default='', max_length=500, null=True)),
                ('last_date', models.DateTimeField(null=True)),
                ('age_range_form', models.IntegerField(null=True)),
                ('age_range_to', models.IntegerField(null=True)),
                ('gender', models.IntegerField()),
                ('job_type', models.IntegerField(null=True)),
                ('job_level', models.IntegerField(null=True)),
                ('edu_qualification', models.CharField(default='', max_length=500, null=True)),
                ('job_context', models.CharField(default='', max_length=500, null=True)),
                ('job_resp', models.CharField(default='', max_length=500, null=True)),
                ('adtn_job_requirements', models.CharField(default='', max_length=500, null=True)),
                ('adtn_job_req', models.CharField(default='', max_length=500, null=True)),
                ('exp_type', models.IntegerField()),
                ('exp_min', models.IntegerField()),
                ('exp_max', models.IntegerField()),
                ('salary_range_flag', models.IntegerField()),
                ('salary_min', models.IntegerField()),
                ('salary_max', models.IntegerField()),
                ('other_benefits', models.CharField(default='', max_length=500, null=True)),
                ('excl_job_flag', models.IntegerField()),
                ('create_by', models.CharField(default='', max_length=20)),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_by', models.CharField(default='', max_length=20)),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jobpost_app.Category')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employer_app.Employer')),
                ('industry', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jobpost_app.Industry')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jobpost_app.Location')),
            ],
        ),
    ]
