# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-19 06:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer_app', '0004_jobpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='excl_job_flag',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='exp_max',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='exp_min',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='exp_type',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='gender',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='job_title',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='salary_max',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='salary_min',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='salary_range_flag',
            field=models.IntegerField(null=True),
        ),
    ]
