# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-10 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobpost_app', '0002_category_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.CharField(default='', max_length=250, unique=True),
        ),
    ]
