# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-12 10:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobpost_app', '0005_industry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
