# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-17 10:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seekerreg',
            name='gender',
            field=models.IntegerField(),
        ),
    ]
